[env:valve]
platform = https://github.com/pioarduino/platform-espressif32.git
board = seeed_xiao_esp32c6
framework = arduino

board_build.partitions = huge_app.csv

lib_deps =
  h2zero/NimBLE-Arduino

monitor_speed = 115200
upload_speed = 921600
upload_protocol = esptool

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
